include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

linter:
  rules:
    prefer_single_quotes: true
    constant_identifier_names: false
    use_key_in_widget_constructors: false
    avoid_classes_with_only_static_members: false
    prefer_relative_imports: true
    require_trailing_commas: true
    file_names: false
    prefer_expression_function_bodies: true
    unnecessary_import: true

analyzer:
  # exclude:
  #   - "**/*.mocks.dart" # Mockito @GenerateMocks
  plugins:
    - dart_code_metrics

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  rules:
    - no-boolean-literal-compare
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - avoid-unnecessary-setstate
    
