name: micro_app_consumo_exame
description: Micro app Exam Consumption.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  table_calendar: ^3.0.6
  intl: ^0.17.0
  path_provider: ^2.0.11
  universal_html: ^2.0.8
  open_file: ^3.2.1
  pdfx: ^2.0.1+2
  dio: ^4.0.6
  equatable: ^2.0.3
  get_it: ^7.2.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flutter_widget_from_html_core: ^0.8.5+3
  flutter_widget_from_html: ^0.8.5
  shared_preferences: ^2.0.15
  file_picker: ^4.6.1
  speech_to_text: ^5.6.1
  image_picker: ^0.8.5+3
  url_launcher: ^6.1.5
  connectivity_plus: ^2.3.9
  textfield_tags: ^2.0.2
  printing: 5.6.5
  easy_mask: ^2.0.1

  base_dependencies:
    git:
      url: git@ssh.dev.azure.com:v3/hiae-innovationlab/ARQUITETURA_BASE/flutlib-arqt-base-dependencies
      ref: null_safety

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  dart_code_metrics: ^4.16.0
  import_sorter: ^4.6.0
  build_runner: ^2.1.11
  mockito: ^5.2.0

dependency_overrides:
  share_plus: 4.0.10+1

scripts: derry.yaml

flutter:
  uses-material-design: true

  assets:
    - assets/images/

import_sorter:
  emojis: false
  comments: false
